# SwiftLint Configuration for Recurra

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - cyclomatic_complexity

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - prohibited_interface_builder
  - redundant_nil_coalescing
  - redundant_type_annotation
  - switch_case_on_newline
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Analyzer rules
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Line length
line_length:
  warning: 120
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

# File length
file_length:
  warning: 500
  error: 1000

# Function body length
function_body_length:
  warning: 50
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 500

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Identifier name
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - x
    - y
    - z

# Type name
type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 40
    error: 60

# Variable name
variable_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60

# Custom rules
custom_rules:
  # No force unwrapping in production code
  no_force_unwrapping:
    name: "No Force Unwrapping"
    regex: '!'
    message: "Force unwrapping should be avoided"
    severity: warning
    excluded: ".*Test.*"

# Excluded paths
excluded:
  - Recurra.xcodeproj
  - .build
  - DerivedData
  - .git

# Included paths
included:
  - Recurra/Recurra

# Reporter
reporter: "xcode"
