name: Build Recurra

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Cache Xcode build artifacts
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
          ~/Library/Caches/com.apple.dt.Xcode
        key: ${{ runner.os }}-xcode-${{ hashFiles('**/project.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-xcode-
          
    - name: Build the app
      run: |
        cd Recurra
        xcodebuild -project Recurra.xcodeproj \
          -scheme Recurra \
          -configuration Release \
          -destination "platform=macOS" \
          -archivePath Recurra.xcarchive \
          archive
          
    - name: Export IPA
      run: |
        cd Recurra
        xcodebuild -exportArchive \
          -archivePath Recurra.xcarchive \
          -exportPath ./build \
          -exportOptionsPlist exportOptions.plist
          
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Recurra-build
        path: Recurra/build/
        retention-days: 30
        
    - name: Create DMG
      run: |
        cd Recurra
        # Create a temporary directory for DMG contents
        mkdir -p dmg_temp
        cp -R build/Recurra.app dmg_temp/
        
        # Create DMG
        hdiutil create -volname "Recurra" -srcfolder dmg_temp -ov -format UDZO Recurra.dmg
        
    - name: Upload DMG
      uses: actions/upload-artifact@v3
      with:
        name: Recurra-DMG
        path: Recurra/Recurra.dmg
        retention-days: 30

  test:
    runs-on: macos-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Run tests
      run: |
        cd Recurra
        xcodebuild test \
          -project Recurra.xcodeproj \
          -scheme Recurra \
          -destination "platform=macOS"
          
  lint:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install SwiftLint
      run: |
        brew install swiftlint
        
    - name: Run SwiftLint
      run: |
        cd Recurra/Recurra
        swiftlint lint --reporter github
