name: Build macOS DMG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build Recurra app
        run: |
          set -eo pipefail
          xcodebuild \
            -project Recurra/Recurra.xcodeproj \
            -scheme Recurra \
            -configuration Release \
            -destination 'platform=macOS,arch=arm64' \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Prepare app bundle
        run: |
          set -eo pipefail
          APP_PATH="build/Build/Products/Release/Recurra.app"
          DEST_DIR="build/artifacts"
          mkdir -p "$DEST_DIR"
          ditto "$APP_PATH" "$DEST_DIR/Recurra.app"

      - name: Create DMG
        run: |
          set -eo pipefail
          ARTIFACT_DIR="build/artifacts"
          DMG_PATH="build/Recurra.dmg"
          hdiutil create -volname "Recurra" -srcfolder "$ARTIFACT_DIR" -ov -format UDZO "$DMG_PATH"

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: Recurra.dmg
          path: build/Recurra.dmg
