name: Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '1.0.0'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-release:
    runs-on: macos-latest
    # Define environment variables from repository/organization secrets.
    # This reduces inline secret references in steps and quiets IDE warnings.
    env:
      CERTIFICATE_P12: ${{ secrets.CERTIFICATE_P12 }}
      CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Cache Xcode build artifacts
      uses: actions/cache@v3
      with:
        path: |
          ~/Library/Developer/Xcode/DerivedData
          ~/Library/Caches/com.apple.dt.Xcode
        key: ${{ runner.os }}-xcode-${{ hashFiles('**/project.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-xcode-
          
    - name: Import Code Signing Certificate
      uses: apple-actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ env.CERTIFICATE_P12 }}
        p12-password: ${{ env.CERTIFICATE_PASSWORD }}
        
    # Notarization credentials are passed directly to notarytool below.
    # If you'd like to use a keychain profile instead, switch to
    # apple-actions/import-notarization-credentials and update the notarytool command.
        
    - name: Build and Archive
      run: |
        cd Recurra
        xcodebuild -project Recurra.xcodeproj \
          -scheme Recurra \
          -configuration Release \
          -destination "platform=macOS" \
          -archivePath Recurra.xcarchive \
          CODE_SIGN_STYLE=Manual \
          CODE_SIGN_IDENTITY="Developer ID Application" \
          PROVISIONING_PROFILE_SPECIFIER="" \
          archive
          
    - name: Export and Notarize
      run: |
        cd Recurra
        xcodebuild -exportArchive \
          -archivePath Recurra.xcarchive \
          -exportPath ./build \
          -exportOptionsPlist exportOptions.plist \
          CODE_SIGN_STYLE=Manual \
          CODE_SIGN_IDENTITY="Developer ID Application"
          
    - name: Create DMG
      run: |
        cd Recurra
        # Create a temporary directory for DMG contents
        mkdir -p dmg_temp
        cp -R build/Recurra.app dmg_temp/
        
        # Create DMG
        hdiutil create -volname "Recurra" -srcfolder dmg_temp -ov -format UDZO Recurra.dmg
        
    - name: Notarize DMG
      run: |
        cd Recurra
        xcrun notarytool submit Recurra.dmg \
          --apple-id "$APPLE_ID" \
          --password "$APPLE_APP_SPECIFIC_PASSWORD" \
          --team-id "$APPLE_TEAM_ID" \
          --wait
          
    - name: Staple Notarization
      run: |
        cd Recurra
        xcrun stapler staple Recurra.dmg
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: Recurra/Recurra.dmg
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
